name: "gerar-jogo-de-cobra-da-grade-de-contribuição-do-github"
description: "Gera um jogo de cobra a partir de uma grade de contribuições de usuários do GitHub. Produza a animação como svg | Generates a snake game from a grid of GitHub user contributions. Output the animation as SVG"
author: "Pjxsantos"

runs:
  using: node20
  main: dist/index.js

inputs:
  github_user_name:
    description: "github user name"
    required: true
  github_token:
    description: "token do github usado para buscar o calendário de contribuições. O padrão é o token de ação se estiver vazio."
    required: false
    default: ${{ github.token }}
  outputs:
    required: false
    default: null
    description: |
      lista de arquivos a serem gerados.
      um arquivo por linha. Cada saída pode ser personalizada com opções como string de consulta.

       opções de string de consulta suportadas:

      - paleta: uma predefinição de cor, uma de [github, github-dark, github-light]
      - color_snake: Cor da cobra
      - color_dots: lista separada por vírgula de cores de pontos.
                      O primeiro é de contribuição 0, depois vai da contribuição mais baixa para a mais alta.
                      São esperadas exatamente 5 cores.
                      - name: gerar-jogo-de-cobra-da-grade-de-contribuição-do-github-pjxsantos-snake@v5.0.2
                      uses: Pjxsantos/snake@v5.0.2
            

    
