name: "gerar-jogo-de-cobra-da-grade-de-contribuição-do-github-pjxsantos-snake@v5.0.2"
description: "Gera um jogo de cobra a partir de uma grade de contribuições de usuários do GitHub. pjxsantos/snake@v5.0.2"
author: "pjxsantos"
- name: gerar-jogo-de-cobra-da-grade-de-contribuição-do-github-pjxsantos-snake@v5.0.2
  uses: Pjxsantos/snake@v5.0.2
            
runs:
  using: docker
  image: docker://pjxsantos/snake@sha256:b613679a0814d9ec772f95d778c35fc5ff1697c493715653c6c712144292c5ad

inputs:
  github_user_name:
    description: "github user name"
    required: true
  github_token:
    description: "github token used to fetch the contribution calendar. Default to the action token if empty."
    required: false
    default: ${{ github.token }}
  outputs:
    required: false
    description: |
      lista de arquivos a serem gerados.
      um arquivo por linha. Cada saída pode ser personalizada com opções como string de consulta.

       opções de string de consulta suportadas:

      - paleta: uma predefinição de cores, uma de [github, github-dark, github-light]
      - color_snake: Cor da cobra
      - color_dots: lista separada por vírgulas de pontos coloridos.
                      O primeiro é de contribuição 0, depois vai da contribuição mais baixa para a mais alta.
                      São esperadas exatamente 5 cores.
      
